[build]
  base = "PWA/OpsmanagerApp"
  publish = "dist"
  command = "pnpm run icons --only-pwa && pnpm run build"

[context.deploy-preview]
  command = "pnpm run icons --only-pwa && pnpm run build"

[context.branch-deploy]
  command = "pnpm run icons --only-pwa && pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200